oauth2:
  github:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}
    accept: application/vnd.github+json
    base-url: https://api.github.com
    login-url: https://github.com/login/oauth/authorize
    redirect-url: http://localhost:8080/callback/github
    access-token-url: https://github.com/login/oauth/access_token

token:
  secret: ${SECRET_KEY}
  access-exp: ${ACCESS_EXP}
  refresh-exp: ${REFRESH_EXP}

spring:
  application:
    name: workaholic
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;
    driver-class-name: org.h2.Driver
    username: ${H2_USER}
    password: ${H2_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

springdoc:
  packages-to-scan: com.project.workaholic
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /index.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha


